[tool.poetry]
name = "dynamic_api_filtering"
version = "0.1.0"
description = "Demo dynamic API filtering"

[tool.poetry.dependencies]

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
